name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Wake up Render backend
        run: curl -s https://sw2-backend-backup1.onrender.com/api/v1/cars || true

      - name: Run Playwright tests (with xvfb)
        run: xvfb-run npx playwright test
        env:
          NEXTAUTH_URL: http://localhost:3000
          NEXTAUTH_SECRET: 'Ey7nTKnggBc0bRN8WUjyShw2qzOZ6KW4fUyqcKBePxY='
          NEXT_PUBLIC_API_URL: https://sw2-backend-backup1.onrender.com
          CI: true

      - name: Upload Playwright Test Report (only if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
